# Generated by Django 5.1.1 on 2024-11-16 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_date',
            new_name='ordered_date',
        ),
    ]
