# Generated by Django 5.1.1 on 2024-11-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_order_date_orderdetail_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
